server:
  port: 8084
  
hsbc:
  hive:
    connectionURL: jdbc:hive2://192.168.204.128:10000/default
    username: root
    password: sa685017
  kerberos:
    keyTabLocation: ~/Security/mourya.keytab
    krb5Location: ~/krb5.conf
    priniciple: mourya@ATHENA.MIT.EDU
security:
  oauth2:
    resource:
       userInfoUri: http://localhost:8080/auth/user    
